lang: ko-KR
timezone: America/Toronto

title: Hestia's Blog
tagline: 일상, 생각들을 기록하는 공간

description: >-
  캐나다 토론토에서 쓰는 일상 블로그.
  도전, 라이프, IT 등 다양한 주제를 기록합니다.

url: "https://hestia-park.github.io"
baseurl: ""

github:
  username: hestia-park

social:
  name: Hestia
  email: ""
  links:
    - https://github.com/hestia-park

theme: jekyll-theme-chirpy

avatar: "" #/assets/img/avatar.jpg

comments:
  active: ""

toc: true

paginate: 10

search: true

google_analytics:
  id: ""
