lang: ko-KR
timezone: America/Toronto

title: Hestia's Blog
tagline: 일상, 생각들을 기록하는 공간

description: >-
  캐나다 토론토에서 쓰는 일상 블로그.
  도전, 라이프, IT 등 다양한 주제를 기록합니다.

url: "https://hestia-park.github.io"
baseurl: ""

github:
  username: hestia-park

social:
  name: Hestia
  email: hestiapark777@gmail.com
  links:
    - https://github.com/hestia-park
    - https://www.notion.so/myplaygroundwithnotion/Resume-11753994d08f8175a341c0bed76a89f9?source=copy_link
  

theme: jekyll-theme-chirpy

avatar: /assets/img/avatar.png

comments:
  active: ""

toc: true

paginate: 10

search: true

google_analytics:
  id: ""
  
html-proofer:
  ignore_urls:
    - "/tags/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
  - scope:
      path: ""
      type: pages
    values:
      layout: page

